#!/bin/bash

# Dacras AI - Claude Code Agent Runner
# Quick launcher for specialized development agents

echo "🎬 Dacras AI - Claude Code Agents"
echo "================================="
echo ""
echo "Select execution mode:"
echo ""
echo "🚀 PARALLEL EXECUTION (Recommended for rapid development):"
echo "P. 🔥 Parallel Mode - Run all 6 agents simultaneously (~60 mins total)"
echo ""
echo "📝 INDIVIDUAL AGENTS:"
echo "1. 🖥️  Frontend Integration Agent - Connect frontend/backend, test components"
echo "2. 🧪  API Testing Agent - Test all API endpoints + Texel.ai integration"  
echo "3. 🎬  Video Processing Agent - Implement video generation with Texel.ai"
echo "4. 🖼️  Image Generation Agent - Add AI image generation features"
echo "5. 🔗  Integration & QA Agent - End-to-end testing, quality assurance"
echo "6. 🚀  DevOps & Monitoring Agent - Deployment, monitoring, infrastructure"
echo ""
echo "0. 📚  View full agent documentation"
echo ""
read -p "Enter your choice (P, 0-6): " choice

case $choice in
    P|p)
        echo ""
        echo "🔥 PARALLEL EXECUTION MODE ACTIVATED!"
        echo "====================================="
        echo ""
        echo "🎯 This will launch all 6 agents in 3 phases for rapid development:"
        echo "   Phase 1: API Testing + DevOps + Image Generation (Parallel)"
        echo "   Phase 2: Video Processing + Frontend Integration (Parallel)" 
        echo "   Phase 3: Integration & QA (Final validation)"
        echo ""
        echo "📋 SETUP REQUIREMENTS:"
        echo "   • 6 Terminal windows ready"
        echo "   • Git committed (clean working directory)"
        echo "   • Node.js and Docker installed"
        echo ""
        echo "📚 Full instructions: PARALLEL_EXECUTION.md"
        echo ""
        echo "🚀 PHASE 1 - Start these 3 agents simultaneously:"
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "TERMINAL 1: API Testing Agent 🧪"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "claude --dangerously-skip-permissions"
        echo ""
        echo "You are an API Testing Specialist for the Dacras AI video ad generation platform. Use the Organized Codebase agent templates as your foundation."
        echo ""
        echo "CODEBASE LOCATION: \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras/backend\""
        echo ""
        echo "API REFERENCE: Read \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras/docs/API_REFERENCE.md\" for complete API specifications."
        echo ""
        echo "PARALLEL EXECUTION MODE: You are running in parallel with other agents. Focus on backend/tests/ directory and create comprehensive test suites. Avoid modifying server.js - only read it for testing purposes."
        echo ""
        echo "PRIMARY TASKS:"
        echo "1. Create comprehensive test suites in backend/tests/ directory"
        echo "2. Set up testing framework (Jest, Supertest, Nock)"
        echo "3. Create mock data factories in backend/tests/fixtures/"
        echo "4. Test all Dacras API endpoints with proper assertions"
        echo "5. Create Texel.ai integration tests with mocking"
        echo "6. Add performance and load testing suites"
        echo "7. Create test configuration and CI/CD setup"
        echo ""
        echo "PARALLEL SAFETY: Only work in backend/tests/, backend/jest.config.js, backend/package.json test scripts."
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "TERMINAL 2: DevOps & Monitoring Agent 🚀"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "claude --dangerously-skip-permissions"
        echo ""
        echo "You are a DevOps & Monitoring Specialist for the Dacras AI video ad generation platform. Use the Organized Codebase agent templates as your foundation."
        echo ""
        echo "CODEBASE LOCATION: \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras\""
        echo ""
        echo "PARALLEL EXECUTION MODE: You are running in parallel with other agents. Focus on deployment, monitoring, and infrastructure files. Avoid modifying core application code."
        echo ""
        echo "PRIMARY TASKS:"
        echo "1. Enhance Docker configurations and docker-compose.yml"
        echo "2. Create Kubernetes deployment manifests in k8s/"
        echo "3. Set up monitoring with Prometheus/Grafana configs"
        echo "4. Create CI/CD pipeline configurations (.github/workflows/)"
        echo "5. Add infrastructure as code (Terraform in infrastructure/)"
        echo "6. Create deployment scripts and health checks"
        echo "7. Set up logging and alerting configurations"
        echo ""
        echo "PARALLEL SAFETY: Work in docker-compose.yml, k8s/, .github/, infrastructure/, monitoring/, deployment/"
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "TERMINAL 3: Image Generation Agent 🖼️"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "claude --dangerously-skip-permissions"
        echo ""
        echo "You are an Image Generation Specialist for the Dacras AI video ad generation platform. Use the Organized Codebase agent templates as your foundation."
        echo ""
        echo "CODEBASE LOCATION: \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras\""
        echo ""
        echo "PARALLEL EXECUTION MODE: You are running in parallel with other agents. Focus on image generation services and utilities. Create new files and avoid modifying existing core files."
        echo ""
        echo "PRIMARY TASKS:"
        echo "1. Create image generation service in backend/services/imageGeneration.js"
        echo "2. Add OpenAI DALL-E integration utilities"
        echo "3. Create image processing pipeline with Sharp.js"
        echo "4. Build image asset management system"
        echo "5. Add image optimization and format conversion"
        echo "6. Create image generation API routes in backend/routes/images.js"
        echo "7. Add image storage and CDN integration"
        echo ""
        echo "PARALLEL SAFETY: Create new files in backend/services/, backend/routes/, backend/utils/images/, avoid modifying server.js directly."
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "⏰ WAIT for Phase 1 completion (~15-20 minutes), then proceed to Phase 2"
        echo ""
        echo "💡 Run 'git status' to monitor progress and avoid conflicts"
        echo "📖 See PARALLEL_EXECUTION.md for Phase 2 and Phase 3 instructions"
        ;;
    1)
        echo ""
        echo "🖥️  Starting Frontend Integration Agent..."
        echo "Copy this prompt into Claude Code:"
        echo ""
        echo "claude --dangerously-skip-permissions"
        echo ""
        echo "You are a Frontend Integration Specialist for the Dacras AI video ad generation platform. Use the Organized Codebase agent templates as your foundation."
        echo ""
        echo "CODEBASE LOCATION: \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras\""
        echo ""
        echo "PRIMARY TASKS:"
        echo "1. Connect React frontend (port 3001) with Node.js backend API (port 3000)"
        echo "2. Implement API client functions for all backend endpoints"
        echo "3. Add proper error handling and loading states"
        echo "4. Create API hook utilities using React Query or SWR"
        echo "5. Test all frontend components thoroughly"
        echo "6. Implement real-time status updates for video generation"
        echo "7. Add form validation and user feedback systems"
        echo "8. Optimize component performance and bundle size"
        echo ""
        echo "Always use the codebase structure and maintain consistency with existing patterns."
        ;;
    2)
        echo ""
        echo "🧪  Starting API Testing Agent..."
        echo "📚  IMPORTANT: This agent will use the API reference documentation"
        echo "    Location: docs/API_REFERENCE.md"
        echo "    Includes: Dacras API + Texel.ai integration specs"
        echo ""
        echo "Copy this prompt into Claude Code:"
        echo ""
        echo "claude --dangerously-skip-permissions"
        echo ""
        echo "You are an API Testing Specialist for the Dacras AI video ad generation platform. Use the Organized Codebase agent templates as your foundation."
        echo ""
        echo "CODEBASE LOCATION: \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras/backend\""
        echo ""
        echo "API REFERENCE: Read \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras/docs/API_REFERENCE.md\" for complete API specifications."
        echo ""
        echo "Create comprehensive test suites for ALL Dacras API endpoints AND Texel.ai integration points. Ensure 95%+ test coverage."
        ;;
    3)
        echo ""
        echo "🎬  Starting Video Processing Agent..."
        echo "📚  IMPORTANT: This agent integrates with Texel.ai API"
        echo "    API Docs: docs/API_REFERENCE.md (Texel.ai section)"
        echo "    Endpoints: Lip-sync, video generation, image processing"
        echo ""
        echo "Copy this prompt into Claude Code:"
        echo ""
        echo "claude --dangerously-skip-permissions"
        echo ""
        echo "You are a Video Processing Specialist for the Dacras AI video ad generation platform. Use the Organized Codebase agent templates as your foundation."
        echo ""
        echo "CODEBASE LOCATION: \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras\""
        echo ""
        echo "API REFERENCE: Read \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras/docs/API_REFERENCE.md\" for Texel.ai integration specifications."
        echo ""
        echo "Implement robust video generation pipeline with complete Texel.ai integration and job management."
        ;;
    4)
        echo ""
        echo "🖼️  Starting Image Generation Agent..."
        echo "Copy this prompt into Claude Code:"
        echo ""
        echo "claude --dangerously-skip-permissions"
        echo ""
        echo "You are an Image Generation Specialist for the Dacras AI video ad generation platform. Use the Organized Codebase agent templates as your foundation."
        echo ""
        echo "CODEBASE LOCATION: \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras\""
        echo ""
        echo "Implement AI image generation features with OpenAI integration and visual asset management."
        ;;
    5)
        echo ""
        echo "🔗  Starting Integration & QA Agent..."
        echo "Copy this prompt into Claude Code:"
        echo ""
        echo "claude --dangerously-skip-permissions"
        echo ""
        echo "You are an Integration & QA Specialist for the Dacras AI video ad generation platform. Use the Organized Codebase agent templates as your foundation."
        echo ""
        echo "CODEBASE LOCATION: \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras\""
        echo ""
        echo "Perform end-to-end testing, system integration validation, and quality assurance processes."
        ;;
    6)
        echo ""
        echo "🚀  Starting DevOps & Monitoring Agent..."
        echo "Copy this prompt into Claude Code:"
        echo ""
        echo "claude --dangerously-skip-permissions"
        echo ""
        echo "You are a DevOps & Monitoring Specialist for the Dacras AI video ad generation platform. Use the Organized Codebase agent templates as your foundation."
        echo ""
        echo "CODEBASE LOCATION: \"/Users/supabowl/Library/Mobile Documents/com~apple~CloudDocs/BHT Promo iCloud/Organized AI/Windsurf/Dacras\""
        echo ""
        echo "Optimize production deployment, implement monitoring, and create scalable infrastructure."
        ;;
    0)
        echo ""
        echo "📚  Opening full agent documentation..."
        if command -v code &> /dev/null; then
            code "CLAUDE_CODE_AGENTS.md"
        elif command -v nano &> /dev/null; then
            nano "CLAUDE_CODE_AGENTS.md" 
        else
            cat "CLAUDE_CODE_AGENTS.md"
        fi
        ;;
    *)
        echo "Invalid choice. Please run the script again and select P, 0-6."
        ;;
esac

echo ""
echo "📚 Key Resources:"
echo "   • Parallel Execution Guide: PARALLEL_EXECUTION.md"
echo "   • API Reference: docs/API_REFERENCE.md (Dacras + Texel.ai)"
echo "   • Agent Documentation: CLAUDE_CODE_AGENTS.md"
echo "   • Testing Config: docs/TESTING_CONFIG.md"
echo ""
echo "💡 Pro tip for parallel mode: Monitor with 'git status' and commit after each phase"
echo ""